/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var m=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},n=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:m(a)}},r="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,
"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},u=aa(this),v=function(a,b){if(b)a:{var c=u;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&r(c,a,{configurable:!0,writable:!0,value:b})}},w=function(){this.u=!1;this.l=null;this.i=void 0;this.h=1;this.J=this.R=0;this.s=null},x=function(a){if(a.u)throw new TypeError("Generator is already running");
a.u=!0};w.prototype.v=function(a){this.i=a};w.prototype.B=function(a){this.s={S:a,$:!0};this.h=this.R||this.J};w.prototype.return=function(a){this.s={return:a};this.h=this.J};var y=function(a,b,c){a.h=c;return{value:b}},A=function(a){this.g=new w;this.ca=a};A.prototype.v=function(a){x(this.g);if(this.g.l)return B(this,this.g.l.next,a,this.g.v);this.g.v(a);return C(this)};
var ba=function(a,b){x(a.g);var c=a.g.l;if(c)return B(a,"return"in c?c["return"]:function(e){return{value:e,done:!0}},b,a.g.return);a.g.return(b);return C(a)};A.prototype.B=function(a){x(this.g);if(this.g.l)return B(this,this.g.l["throw"],a,this.g.v);this.g.B(a);return C(this)};
var B=function(a,b,c,e){try{var f=b.call(a.g.l,c);if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");if(!f.done)return a.g.u=!1,f;var g=f.value}catch(d){return a.g.l=null,a.g.B(d),C(a)}a.g.l=null;e.call(a.g,g);return C(a)},C=function(a){for(;a.g.h;)try{var b=a.ca(a.g);if(b)return a.g.u=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,a.g.B(c)}a.g.u=!1;if(a.g.s){b=a.g.s;a.g.s=null;if(b.$)throw b.S;return{value:b.return,done:!0}}return{value:void 0,done:!0}},ca=
function(a){this.next=function(b){return a.v(b)};this.throw=function(b){return a.B(b)};this.return=function(b){return ba(a,b)};this[Symbol.iterator]=function(){return this}},da=function(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,f){function g(d){d.done?e(d.value):Promise.resolve(d.value).then(b,c).then(g,f)}g(a.next())})},D=function(a){return da(new ca(new A(a)))};
v("Symbol",function(a){if(a)return a;var b=function(g,d){this.O=g;r(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.O};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0,f=function(g){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+e++,g)};return f});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=u[b[c]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&r(e.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(m(this))}})}return a});var ea=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
v("Promise",function(a){function b(){this.j=null}function c(d){return d instanceof f?d:new f(function(h){h(d)})}if(a)return a;b.prototype.H=function(d){if(null==this.j){this.j=[];var h=this;this.I(function(){h.T()})}this.j.push(d)};var e=u.setTimeout;b.prototype.I=function(d){e(d,0)};b.prototype.T=function(){for(;this.j&&this.j.length;){var d=this.j;this.j=[];for(var h=0;h<d.length;++h){var k=d[h];d[h]=null;try{k()}catch(l){this.P(l)}}}this.j=null};b.prototype.P=function(d){this.I(function(){throw d;
})};var f=function(d){this.o=0;this.A=void 0;this.m=[];this.M=!1;var h=this.F();try{d(h.resolve,h.reject)}catch(k){h.reject(k)}};f.prototype.F=function(){function d(l){return function(p){k||(k=!0,l.call(h,p))}}var h=this,k=!1;return{resolve:d(this.ea),reject:d(this.G)}};f.prototype.ea=function(d){if(d===this)this.G(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof f)this.ga(d);else{a:switch(typeof d){case "object":var h=null!=d;break a;case "function":h=!0;break a;default:h=
!1}h?this.da(d):this.K(d)}};f.prototype.da=function(d){var h=void 0;try{h=d.then}catch(k){this.G(k);return}"function"==typeof h?this.ha(h,d):this.K(d)};f.prototype.G=function(d){this.N(2,d)};f.prototype.K=function(d){this.N(1,d)};f.prototype.N=function(d,h){if(0!=this.o)throw Error("Cannot settle("+d+", "+h+"): Promise already settled in state"+this.o);this.o=d;this.A=h;2===this.o&&this.fa();this.U()};f.prototype.fa=function(){var d=this;e(function(){if(d.ba()){var h=u.console;"undefined"!==typeof h&&
h.error(d.A)}},1)};f.prototype.ba=function(){if(this.M)return!1;var d=u.CustomEvent,h=u.Event,k=u.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):"function"===typeof h?d=new h("unhandledrejection",{cancelable:!0}):(d=u.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.A;return k(d)};f.prototype.U=function(){if(null!=this.m){for(var d=0;d<this.m.length;++d)g.H(this.m[d]);
this.m=null}};var g=new b;f.prototype.ga=function(d){var h=this.F();d.C(h.resolve,h.reject)};f.prototype.ha=function(d,h){var k=this.F();try{d.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.then=function(d,h){function k(t,z){return"function"==typeof t?function(P){try{l(t(P))}catch(Q){p(Q)}}:z}var l,p,q=new f(function(t,z){l=t;p=z});this.C(k(d,l),k(h,p));return q};f.prototype.catch=function(d){return this.then(void 0,d)};f.prototype.C=function(d,h){function k(){switch(l.o){case 1:d(l.A);
break;case 2:h(l.A);break;default:throw Error("Unexpected state: "+l.o);}}var l=this;null==this.m?g.H(k):this.m.push(k);this.M=!0};f.resolve=c;f.reject=function(d){return new f(function(h,k){k(d)})};f.race=function(d){return new f(function(h,k){for(var l=n(d),p=l.next();!p.done;p=l.next())c(p.value).C(h,k)})};f.all=function(d){var h=n(d),k=h.next();return k.done?c([]):new f(function(l,p){function q(P){return function(Q){t[P]=Q;z--;0==z&&l(t)}}var t=[],z=0;do t.push(void 0),z++,c(k.value).C(q(t.length-
1),p),k=h.next();while(!k.done)})};return f});v("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});v("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var f=e.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var g=e[c];if(g===b||Object.is(g,b))return!0}return!1}});
v("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
var fa=function(a,b){a instanceof String&&(a+="");var c=0,e=!1,f={next:function(){if(!e&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}e=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f};v("Array.prototype.keys",function(a){return a?a:function(){return fa(this,function(b){return b})}});var ha=this||self;var E=["NONE","ERROR","WARNING","INFO","DEBUG"],ia={cep_proxy_url:!0,enable_auto_enrollment:!0,enable_certificate_renewal:!0,allow_machine_cert_enrollment:!0,user_enrollment_templates:!0,device_enrollment_templates:!0,placeholder_values:!0,company_info:!0,log_level:!0,user_cert_request_values:!0,device_cert_request_values:!0,signature_algo:!0,pending_ui_enabled:!0,renew_hours_before_expiry:!0,renew_reminder_interval:!0,request_timeout_seconds:!0,va_api_key:!0,va_enabled:!0,va_google_url:!0,va_shared_secret:!0,
va_request_timeout_seconds:!0,service_account_name:!0,service_account_password:!0,client_authentication:!0,use_key_based_renewal:!0,ces_renewal_url:!0,service_account_host:!0,service_account_host_password_mask:!0},ja=E.indexOf("WARNING"),F=E.indexOf("INFO"),G=E.indexOf("DEBUG"),H=function(a,b){0<b&&b<=G&&b<E.length&&console.log(E[b]+": "+a)},ka=function(a){return new Promise(function(b,c){try{chrome.enterprise.platformKeys.getCertificates(a,function(e){chrome.runtime.lastError?c(chrome.runtime.lastError):
b(e)})}catch(e){c(e)}})},I=function(){return new Promise(function(a,b){try{chrome.storage.local.get("ignored_renewal_requests",function(c){c&&c.ignored_renewal_requests?a(c.ignored_renewal_requests):a([])})}catch(c){b(c)}})},la=function(a){I().then(function(b){b.push(a);chrome.storage.local.set({ignored_renewal_requests:b},function(){})})},na=function(a,b,c){var e,f;D(function(g){if(1==g.h)return y(g,ma(a),2);if(e=g.i)return g.return();f=a.notAfter.value;0<b&&f.setHours(f.getHours()-b);chrome.alarms.create(J(a),
{when:f.getTime(),periodInMinutes:60*c});g.h=0})},ma=function(a){var b;return D(function(c){b=J(a);return c.return(new Promise(function(e,f){chrome.alarms.get(b,function(g){chrome.runtime.lastError?f(chrome.runtime.lastError):e(void 0!=g?!0:!1)})}))})},K=function(a){var b,c,e,f,g,d,h,k,l,p;return D(function(q){if(1==q.h)return b=null,y(q,I(),2);if(3!=q.h)return c=q.i,0<c.length&&H("The following certificates are explicitly ignored for renewal by the user: "+c.join("\n"),G),y(q,ka(a),3);e=q.i;f=n(e);
for(g=f.next();!g.done;g=f.next())if(d=g.value,h=window.org.pkijs.fromBER(d),k=new window.org.pkijs.simpl.CERT({schema:h.result}),null==b||b.notAfter.value<k.notAfter.value)c.includes(J(k))||(b=k);if(!b)return q.return(null);l=new Date;p=b.notAfter.value;return p<l?q.return(null):q.return(b)})},oa=function(a){var b,c,e,f;return D(function(g){if(1==g.h)return b="user",y(g,K("user"),2);if(3!=g.h)return e=c=g.i,a?y(g,K("system"),3):e?g.return({slot:b,D:e}):g.return(null);(f=g.i)&&(!c||f.notAfter.value<
c.notAfter.value)&&(b="system",e=f);return e?g.return({slot:b,D:e}):g.return(null)})},M=function(){var a=L.allow_machine_cert_enrollment&&L.use_key_based_renewal,b=L.renew_hours_before_expiry?L.renew_hours_before_expiry:120,c=L.renew_reminder_interval?L.renew_reminder_interval:24;chrome.enterprise&&oa(a).then(function(e){e?(na(e.D,b,c),pa(e.D,b)):H("No valid certificate found for renewal",G)})},pa=function(a,b){if(qa(a,b))H("Certificate is still valid beyond configured offset.",G);else{H("Certificate will expire before configured offset.",
G);a=J(a);b=[];var c={};c.title=chrome.i18n.getMessage("renewal_notification_remind");b.push(c);c={};c.title=chrome.i18n.getMessage("renewal_notification_ignore");b.push(c);chrome.notifications.create(a,{type:"basic",title:chrome.i18n.getMessage("renewal_notification_title"),iconUrl:"img/128.png",message:chrome.i18n.getMessage("renewal_notification_message"),buttons:b},function(){})}},qa=function(a,b){var c=new Date;return a.notAfter.value.setHours(a.notAfter.value.getHours()-(void 0===b?0:b))>c},
J=function(a){return(new Uint8Array(a.serialNumber.value_block.value_hex)).toString()},ra=function(a,b,c){var e,f;return D(function(g){switch(g.h){case 1:if(!a){g.h=2;break}return y(g,K("system"),3);case 3:return(e=g.i)?g.return(null):b?g.return({slot:"system",method:"kerberos"}):c?g.return({slot:"system",method:"service_account"}):g.return(null);case 2:return y(g,K("user"),4);case 4:return(f=g.i)?g.return(null):b?g.return({slot:"user",method:"kerberos"}):g.return(null)}})};var O=function(){try{chrome.storage.onChanged.addListener(this.X),chrome.runtime.onInstalled.addListener(this.L),chrome.runtime.onMessage.addListener(sa),chrome.alarms.onAlarm.addListener(this.V),chrome.notifications.onClicked.addListener(this.Z),chrome.notifications.onButtonClicked.addListener(this.Y),chrome.browserAction.onClicked.addListener(this.W)}catch(a){}this.L({});N(function(){M();ta()})};
O.prototype.X=function(a,b){H("Handling managed policy change from control panel.",F);if("managed"==b){var c=L.enable_auto_enrollment,e;for(e in a)L[e]=a[e].newValue;R("ccrTabOpenedPreviously",function(f){f=void 0===f||void 0===f.ccrTabOpenedPreviously||!f.ccrTabOpenedPreviously;(!1===c||void 0===c&&f)&&S()})}};
var sa=function(a,b,c){H("Handling request from the frontend.",F);if(void 0!==b.tab)switch(a.action){case "policyRequest":c(JSON.stringify(L));break;case "policyStore":a=JSON.parse(a.data),null!==a&&void 0!==a&&"object"==typeof a&&(L=a)}};O.prototype.L=function(a){void 0===a.OnInstalledReason?R("ccrInstalledPreviously",this.aa):T(a.OnInstalledReason)};O.prototype.V=function(a){"certificate_renewal_alarm"==a.name&&(H("Certificate renewal alarm triggered.",G),M())};
O.prototype.Z=function(a){"ccrAutoEnrollmentNotification"==a?U(!1,"auto_provision"):U(!1,"renewal");chrome.notifications.clear(a)};O.prototype.Y=function(a,b){1==b&&(la(a),H("Ignore certificate renewal request.",F));chrome.notifications.clear(a)};O.prototype.W=function(){U(!1,"none")};var R=function(a,b){void 0!==chrome.storage&&chrome.storage.local.get(a,b)};
O.prototype.aa=function(a){var b="";void 0!==a&&void 0!==a.ccrInstalledPreviously&&a.ccrInstalledPreviously||(b="install",V("ccrInstalledPreviously"));T(b)};
var V=function(a){var b={};b[a]=!0;chrome.storage.local.set(b,function(){})},T=function(a){if("install"===a)H("New install detected.",F),N(function(){S()});else{H("New update detected.",F);var b=L.enable_auto_enrollment;R("ccrTabOpenedPreviously",function(c){N(function(){var e=void 0===c||void 0===c.ccrTabOpenedPreviously||!c.ccrTabOpenedPreviously;(!1===b||void 0===b&&e)&&S()})})}},S=function(){L.enable_auto_enrollment&&U(!0,"none")},U=function(a,b){var c="html/request_certificate.html";"none"!=
b&&(c+="?autoEnrollmentType="+b);b={url:c};a?chrome.tabs.create(b,function(){V("ccrTabOpenedPreviously")}):chrome.tabs.create(b,function(){})},N=function(a){if(chrome.storage&&chrome.storage.managed)try{chrome.storage.managed.get(function(b){if(0==Object.keys(b).length)H("No managed policy found. Consumer mode.",F);else{H("Managed policy found. Enterprise mode.",F);for(var c in b){var e=b[c];ia[c]?L[c]=e:(e=chrome.i18n.getMessage("invalid_policy_var",[c,e.toString()]),H(e,ja))}}a()})}catch(b){}},
ta=function(){var a=L.allow_machine_cert_enrollment,b="kerberos"===L.client_authentication,c=ua();ra(a,b,c).then(function(e){e&&chrome.notifications.create("ccrAutoEnrollmentNotification",{type:"basic",title:chrome.i18n.getMessage("auto_enrollment_notification_title"),iconUrl:"img/128.png",message:chrome.i18n.getMessage("auto_enrollment_notification_message"),requireInteraction:!0},function(){})})},ua=function(){var a=L.service_account_password,b=L.service_account_host;return L.service_account_name&&
a||b?L.device_enrollment_templates?!0:(H("No device enrollment templates configured, skipped device auto-enrollment/renewal.",G),!1):(H("No service account configured, skipped device auto-enrollment/renewal.",G),!1)},W=["ccr","background"],X=ha;W[0]in X||"undefined"==typeof X.execScript||X.execScript("var "+W[0]);for(var Y;W.length&&(Y=W.shift());)W.length||void 0===O?X=X[Y]&&X[Y]!==Object.prototype[Y]?X[Y]:X[Y]={}:X[Y]=O;var L={},Z;void 0===Z&&(Z=new O);
